name: firebase_auth_example
description: Demonstrates how to use the firebase_auth plugin.

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  firebase_auth:
    path: ../
  firebase_core:
    path: ../../../firebase_core/firebase_core
  flutter:
    sdk: flutter
  flutter_signin_button: ^2.0.0 
  github_sign_in: ^0.0.5-dev.4
  google_sign_in: ^5.1.0
  twitter_login: ^4.0.1

dependency_overrides:
  firebase_auth:
    path: ../
  firebase_auth_platform_interface:
    path: ../../firebase_auth_platform_interface
  firebase_auth_web:
    path: ../../firebase_auth_web
  firebase_core:
    path: ../../../firebase_core/firebase_core
  firebase_core_platform_interface:
    path: ../../../firebase_core/firebase_core_platform_interface
  firebase_core_web:
    path: ../../../firebase_core/firebase_core_web

dev_dependencies:
  drive: 1.0.0-1.0.nullsafety.1
  flutter_driver:
    sdk: flutter
  http: ^0.13.3
  test: any

flutter:
  uses-material-design: true
