// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL0nm0G0GoGwXZ1O0iwG_STbbA2NnooG8',
    appId: '1:886042531161:web:1a9e445a6df73b6d4ea848',
    messagingSenderId: '886042531161',
    projectId: 'loginapp-83f3d',
    authDomain: 'loginapp-83f3d.firebaseapp.com',
    storageBucket: 'loginapp-83f3d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAznHidqjWRRTyR8Wjx10ib7gQsPF21dSE',
    appId: '1:886042531161:android:892f766fcce9e5ab4ea848',
    messagingSenderId: '886042531161',
    projectId: 'loginapp-83f3d',
    storageBucket: 'loginapp-83f3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKQeTy2TDjigdEjHpai5xk4uNWlHucEfQ',
    appId: '1:886042531161:ios:4cef0b36a0294f254ea848',
    messagingSenderId: '886042531161',
    projectId: 'loginapp-83f3d',
    storageBucket: 'loginapp-83f3d.appspot.com',
    androidClientId: '886042531161-vcl1ao8dd89t1sjnuub7can9upuenk12.apps.googleusercontent.com',
    iosClientId: '886042531161-r3euc7ktshcdqb86rif13lciso07dm7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginapp',
  );
}
